# Generated by Django 4.2.3 on 2023-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomSongs', '0002_remove_song_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
