# Generated by Django 4.2.3 on 2023-07-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomSongs', '0004_songsugge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsugge',
            old_name='name',
            new_name='Sname',
        ),
    ]
