# Generated by Django 4.2.3 on 2023-07-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomSongs', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
