# Generated by Django 4.2.3 on 2023-07-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomSongs', '0009_remove_suggestions_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='songName',
            new_name='name',
        ),
    ]
